-- data cleaning of patient table

-- remove patient rows where first name is missing
-- standardize firstname and lastname to proper case and create a new full name column
-- gender values should be either male or female
-- split citystatecountry into city, state and country columns separately

CREATE TABLE PATIENT_CLEAN(
	PATIENTID VARCHAR(20) PRIMARY KEY,
    FULLNAME VARCHAR(120),
    GENDER VARCHAR(10),
    DOB DATE,
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50)
);

INSERT INTO PATIENT_CLEAN(PATIENTID, FULLNAME, GENDER, DOB, CITY, STATE, COUNTRY) 
SELECT 
P.PATIENTID, 

CONCAT(UPPER(LEFT(LTRIM(RTRIM(P.FIRSTNAME)), 1)) , LOWER(SUBSTRING(LTRIM(RTRIM(P.FIRSTNAME)) , 2 , LENGTH(LTRIM(RTRIM(P.FIRSTNAME))))) , ' ',

UPPER(LEFT(LTRIM(RTRIM(P.LASTNAME)), 1)) , LOWER(SUBSTRING(LTRIM(RTRIM(P.LASTNAME)) , 2 , LENGTH(LTRIM(RTRIM(P.LASTNAME))))) )
AS FULLNAME,

CASE 
WHEN P.GENDER = 'M' THEN 'MALE'
WHEN P.GENDER = 'F' THEN 'FEMALE'
ELSE P.GENDER
END AS GENDER,

P.DOB, 

SUBSTRING_INDEX(
	REPLACE(P.CITYSTATECOUNTRY , ',' , '.'),
    '.',
    1)
AS CITY,

SUBSTRING_INDEX(
SUBSTRING_INDEX(
	REPLACE(P.CITYSTATECOUNTRY, ',','.'),
    '.',
    2),
    '.',
    -1)
AS STATE,

SUBSTRING_INDEX(
	REPLACE(P.CITYSTATECOUNTRY,',','.'),
    '.',
    -1)
AS COUNTRY 

FROM PATIENT P 
WHERE P.FIRSTNAME IS NOT NULL;

SELECT * FROM PATIENT_CLEAN;

-- data cleaning (department table)

-- remove departments where department category is missing
-- drop HOD and departmentName columns
-- use specialization as departmentName column

SELECT * FROM DEPARTMENT;

CREATE TABLE DEPARTMENT_CLEAN(
	DEPARTMENTID VARCHAR(10) PRIMARY KEY,
    DEPARTMENTNAME VARCHAR(50),
    DEPARTMENT_CATEGORY VARCHAR(50)
);

INSERT INTO DEPARTMENT_CLEAN(DEPARTMENTID, DEPARTMENTNAME, DEPARTMENT_CATEGORY)
SELECT
D.DEPARTMENTID, 
D.SPECIALIZATION AS DEPARTMENT_NAME,
D.DEPARTMENTCATEGORY 
FROM DEPARTMENT D
WHERE D.DEPARTMENTCATEGORY IS NOT NULL;

SELECT * FROM DEPARTMENT_CLEAN;

-- patient visits table

-- merge all yearly visit tables (2020-2025) into one consolidated PatientVisits table

SELECT * FROM PATIENTVISITS_2020_2021;

CREATE TABLE PATIENT_VISITS(
VISIT_ID VARCHAR(10) PRIMARY KEY,
PATIENT_ID VARCHAR(10),
DOCTOR_ID VARCHAR(20),
DEPARTMENT_ID VARCHAR(20),
DIAGNOSIS_ID VARCHAR(20),
TREATMENT_ID VARCHAR(20),
PAYMENT_METHOD_ID VARCHAR(20),
VISIT_DATE DATE,
VISIT_TIME TIME,
DISCHARGE_DATE DATE,
BILL_AMOUNT DECIMAL(18,2),
INSURANCE_AMOUNT DECIMAL(18,2),
SATISFACTION_SCORE INT,
WAIT_TIME_MINUTES INT ,

FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT_CLEAN(PATIENTID),
FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTORID),
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT_CLEAN(DEPARTMENTID),
FOREIGN KEY (DIAGNOSIS_ID) REFERENCES DIAGNOSIS(DIAGNOSISID),
FOREIGN KEY (TREATMENT_ID) REFERENCES TREATMENT(TREATMENTID),
FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENTMETHOD(PAYMENTMETHODID)
);

INSERT INTO PATIENT_VISITS(
VISIT_ID, PATIENT_ID, DOCTOR_ID, DEPARTMENT_ID, DIAGNOSIS_ID, TREATMENT_ID, PAYMENT_METHOD_ID, 
VISIT_DATE, VISIT_TIME, DISCHARGE_DATE, BILL_AMOUNT, INSURANCE_AMOUNT, SATISFACTION_SCORE, WAIT_TIME_MINUTES
) 
SELECT * FROM PATIENTVISITS_2020_2021
UNION ALL 
SELECT * FROM PATIENTVISITS_2022_2023
UNION ALL 
SELECT * FROM PATIENTVISITS_2024
UNION ALL
SELECT * FROM PATIENTVISITS_2025;

SELECT * FROM PATIENT_VISITS;
SELECT DISTINCT(YEAR(VISIT_DATE)) FROM PATIENT_VISITS;