USE HOSPITAL_DB;
SHOW TABLES;

-- for each doctor count how many distinct patients they've treated
SELECT DOCTORID FROM DOCTOR;
SELECT DOCTOR_ID, PATIENT_ID FROM PATIENT_VISITS;

SELECT D.DOCTORID, 
CONCAT(D.FIRSTNAME, ' ', D.LASTNAME) AS DOCTOR_NAME,
COUNT(DISTINCT PV.PATIENT_ID) AS DISTINCT_PATIENTS_TREATED
FROM DOCTOR D 
JOIN PATIENT_VISITS PV 
ON D.DOCTORID = PV.DOCTOR_ID
GROUP BY D.DOCTORID, D.FIRSTNAME, D.LASTNAME
ORDER BY DISTINCT_PATIENTS_TREATED DESC;

-- show the revenue split by each payment method along with total visits
DESC PATIENT_VISITS;

SELECT PM.PAYMENTMETHOD, SUM(PV.BILL_AMOUNT) AS TOTAL_REVENUE,
COUNT(*) AS TOTAL_VISITS 
FROM PATIENT_VISITS PV
JOIN PAYMENTMETHOD PM
ON PV.PAYMENT_METHOD_ID = PM.PAYMENTMETHODID
GROUP BY PM.PAYMENTMETHOD 
ORDER BY TOTAL_REVENUE DESC;

-- categorize patients into age groups and calculate the average bill amount for each age band
-- (Assume at the time of visit based on visit date)

SELECT AGE_GROUP, 
ROUND(AVG(BILL_AMOUNT),2) AS AVG_BILL_AMOUNT,
COUNT(*) AS TOTAL_VISITS
FROM(
	SELECT PV.BILL_AMOUNT,
    CASE
    WHEN TIMESTAMPDIFF(YEAR, P.DOB, PV.VISIT_DATE) <= 18 THEN 'CHILD'
    WHEN TIMESTAMPDIFF(YEAR, P.DOB, PV.VISIT_DATE) BETWEEN 19 AND 35 THEN 'YOUNG ADULT'
    WHEN TIMESTAMPDIFF(YEAR, P.DOB, PV.VISIT_DATE) BETWEEN 36 AND 60 THEN 'ADULT'
    ELSE 'SENIOR'
    END AS AGE_GROUP
    FROM PATIENT_VISITS PV
    JOIN PATIENT P
    ON PV.PATIENT_ID = P.PATIENTID
) X
GROUP BY AGE_GROUP
ORDER BY AVG_BILL_AMOUNT DESC;

-- find total revenue and number of visits for each department
SELECT D.DEPARTMENTID, D.DEPARTMENTNAME, COUNT(*) AS VISIT_COUNT
FROM DEPARTMENT D
JOIN PATIENT_VISITS PV
ON D.DEPARTMENTID = PV.DEPARTMENT_ID
GROUP BY D.DEPARTMENTID , D.DEPARTMENTNAME
ORDER BY VISIT_COUNT DESC;

-- rank departments based on their total revenue within each department category

-- overall department
SELECT D.DEPARTMENTNAME AS DEPARTMENT_NAME,
SUM(PV.BILL_AMOUNT) AS TOTAL_REVENUE,
RANK() OVER (ORDER BY SUM(PV.BILL_AMOUNT) DESC) AS DEPT_RANK
FROM DEPARTMENT D 
JOIN PATIENT_VISITS PV
ON D.DEPARTMENTID = PV.DEPARTMENT_ID
GROUP BY D.DEPARTMENTNAME;

-- inclusing category
SELECT * FROM DEPARTMENT_CLEAN;
WITH DEPT_REVENUE AS 
(
	SELECT D.DEPARTMENT_CATEGORY,
    D.DEPARTMENTNAME,
    SUM(PV.BILL_AMOUNT) AS TOTAL_REVENUE
    FROM PATIENT_VISITS PV
    JOIN DEPARTMENT_CLEAN D 
    ON PV.DEPARTMENT_ID = D.DEPARTMENTID
    GROUP BY D.DEPARTMENT_CATEGORY, D.DEPARTMENTNAME
)

SELECT *,
RANK() OVER (PARTITION BY DEPARTMENT_CATEGORY ORDER BY TOTAL_REVENUE DESC) AS DEPARTMENT_RANK
FROM DEPT_REVENUE
ORDER BY DEPARTMENT_CATEGORY, DEPARTMENT_RANK;

-- for each department, find the average satisfaction score and average wait time
SELECT D.DEPARTMENTNAME AS DEPARTMENT_NAME,
AVG(PV.SATISFACTION_SCORE) AS SATISFACTION_SCORE,
AVG(PV.WAIT_TIME_MINUTES) AS WAITING_TIME_IN_MINS
FROM DEPARTMENT D
JOIN PATIENT_VISITS PV
ON D.DEPARTMENTID = PV.DEPARTMENT_ID
GROUP BY D.DEPARTMENTNAME
ORDER BY SATISFACTION_SCORE DESC, WAITING_TIME_IN_MINS DESC;

-- compare the total number of hospital visits on weekdays vs weekends

SELECT * FROM PATIENT_VISITS;
SELECT VISIT_TYPE,
COUNT(*) AS TOTAL_VISITS
FROM(
	SELECT 
    CASE
    WHEN DAYOFWEEK(VISIT_DATE) IN (1,7) THEN 'WEEKEND'
    ELSE 'WEEKDAY'
    END AS VISIT_TYPE
    FROM PATIENT_VISITS
) X
GROUP BY VISIT_TYPE;

-- for each month calculate the total visits and a running cumulative total of visits

WITH MONTHLY_VISITS AS
(
	SELECT YEAR(VISIT_DATE) AS YEAR_,
    MONTH(VISIT_DATE) AS MONTH_NO,
    MONTHNAME(VISIT_DATE) AS MONTH_NAME,
    COUNT(*) AS TOTAL_VISITS
    FROM PATIENT_VISITS
    GROUP BY YEAR(VISIT_DATE), MONTH(VISIT_DATE), MONTHNAME(VISIT_DATE)
)

SELECT MONTH_NAME, YEAR_, TOTAL_VISITS, 
SUM(TOTAL_VISITS) OVER (ORDER BY YEAR_, MONTH_NO) AS RUNNING_TOTAL_VISITS
FROM MONTHLY_VISITS
ORDER BY YEAR_, MONTH_NO;

-- find the doctors with the highest average satisfaction score (minimum 100 visits)
WITH SATISFACTION_AVG AS (
SELECT 
CONCAT(D.FIRSTNAME, ' ', D.LASTNAME) AS DOCTOR_NAME,
COUNT(*) AS VISIT_COUNT,
AVG(PV.SATISFACTION_SCORE) AS SATISFACTION_SCORE
FROM DOCTOR D
JOIN PATIENT_VISITS PV
ON D.DOCTORID = PV.DOCTOR_ID
GROUP BY DOCTOR_NAME)

SELECT * FROM SATISFACTION_AVG 
WHERE VISIT_COUNT >= 100
ORDER BY SATISFACTION_SCORE DESC;

-- identify the most commonly prescribed treatment for each diagnosis

WITH TREATMENT_COUNT AS 
(
	SELECT D.DIAGNOSISNAME,
    T.TREATMENTNAME, 
    COUNT(*) AS TIMES_PRESCRIBED
    FROM PATIENT_VISITS PV
    JOIN DIAGNOSIS D
    ON PV.DIAGNOSIS_ID = D.DIAGNOSISID
    JOIN TREATMENT T
    ON T.TREATMENTID = PV.TREATMENT_ID
    GROUP BY D.DIAGNOSISNAME, T.TREATMENTNAME
)

SELECT DIAGNOSISNAME, TREATMENTNAME, TIMES_PRESCRIBED
FROM 
(
	SELECT * ,
    RANK() OVER( PARTITION BY DIAGNOSISNAME ORDER BY TIMES_PRESCRIBED DESC) AS RK
    FROM TREATMENT_COUNT
) X
WHERE RK = 1
ORDER BY TIMES_PRESCRIBED DESC;